# Generated by Django 3.1.6 on 2021-02-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210225_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
