# Generated by Django 3.1.6 on 2021-03-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210226_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(choices=[('Not Viewed', 'Not Viewed'), ('Viewed', 'Viewed'), ('Rejected', 'Rejected'), ('Continues', 'Continues'), ('Selected', 'Selected')], max_length=64),
        ),
    ]
